# typed: false
# frozen_string_literal: true

# Homebrew formula for beeper-tui. Generated by src/packaging/homebrew.ts on
# release — do not edit by hand.
class BeeperTui < Formula
  desc "Keyboard-first terminal client for Beeper"
  homepage "https://github.com/mitchmalone/beeptui"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.1.0/beeper-tui-darwin-arm64"
      sha256 "2c459963d0d8a0808e90b1aed1f9c225683107774358409f8907d0ef911fccc4"

      def install
        bin.install "beeper-tui-darwin-arm64" => "beeper-tui"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.1.0/beeper-tui-linux-x64"
      sha256 "ee3b23a51e056abe629056f3107b24209cac25cb1124a85e99388b0d5fc62667"

      def install
        bin.install "beeper-tui-linux-x64" => "beeper-tui"
      end
    end
  end

  test do
    assert_match "beeper-tui", shell_output("#{bin}/beeper-tui --version")
  end
end
