# typed: false
# frozen_string_literal: true

# Homebrew formula for beeptui. Generated by src/packaging/homebrew.ts on
# release — do not edit by hand.
class Beeptui < Formula
  desc "Keyboard-first terminal client for Beeper"
  homepage "https://github.com/mitchmalone/beeptui"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.4.0/beeptui-darwin-arm64"
      sha256 "ae07b83bc914d3e3f2477e2322d4f12564f29476c3bba82c6d921bd1bf4f758c"

      def install
        bin.install "beeptui-darwin-arm64" => "beeptui"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.4.0/beeptui-linux-x64"
      sha256 "5f94b23bc2ff2e1762304f5fdd199da205e0a58bc95e315302141d7ebdc0324e"

      def install
        bin.install "beeptui-linux-x64" => "beeptui"
      end
    end
  end

  test do
    assert_match "beeptui", shell_output("#{bin}/beeptui --version")
  end
end
