# typed: false
# frozen_string_literal: true

# Homebrew formula for beeptui. Generated by src/packaging/homebrew.ts on
# release — do not edit by hand.
class Beeptui < Formula
  desc "Keyboard-first terminal client for Beeper"
  homepage "https://github.com/mitchmalone/beeptui"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.4.1/beeptui-darwin-arm64"
      sha256 "81fb5135c89f7797ea700c2087fe182f64787584192a0b2a67348aab16fd916a"

      def install
        bin.install "beeptui-darwin-arm64" => "beeptui"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.4.1/beeptui-linux-x64"
      sha256 "3ce9de73dfabc86e0d18b0245471cba1d47f3407f55143e433f5d1cf6db4d9a2"

      def install
        bin.install "beeptui-linux-x64" => "beeptui"
      end
    end
  end

  test do
    assert_match "beeptui", shell_output("#{bin}/beeptui --version")
  end
end
