# typed: false
# frozen_string_literal: true

# Homebrew formula for beeptui. Generated by src/packaging/homebrew.ts on
# release — do not edit by hand.
class Beeptui < Formula
  desc "Keyboard-first terminal client for Beeper"
  homepage "https://github.com/mitchmalone/beeptui"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.3.0/beeptui-darwin-arm64"
      sha256 "9833cc0ef96752e840bc693ef72155d940e0f3747e3dda69a8f426e6b6f5bd09"

      def install
        bin.install "beeptui-darwin-arm64" => "beeptui"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mitchmalone/beeptui/releases/download/v0.3.0/beeptui-linux-x64"
      sha256 "330be7675c4f7f369cc1395c246d77d7da60e217a26152e337b369e2696540f2"

      def install
        bin.install "beeptui-linux-x64" => "beeptui"
      end
    end
  end

  test do
    assert_match "beeptui", shell_output("#{bin}/beeptui --version")
  end
end
